SET search_path TO projet;


-- Schéma

DROP SCHEMA IF EXISTS projet CASCADE;
CREATE SCHEMA projet AUTHORIZATION projet;
GRANT ALL PRIVILEGES ON SCHEMA projet TO projet;


-- Tables

CREATE TABLE compte (
	IdCompte		INT			 	NOT NULL	GENERATED BY DEFAULT AS IDENTITY,
	Pseudo			VARCHAR(25)		NOT NULL,
	MotDePasse		VARCHAR(25) 	NOT NULL,
	Email			VARCHAR(100)	NOT NULL,
	PRIMARY KEY (IdCompte)
);
CREATE UNIQUE INDEX idx_compte_pseudo ON compte (Pseudo ASC);

CREATE TABLE role (
	IdCompte		INT				NOT NULL,
	Role			VARCHAR(20)		NOT NULL,
	CHECK( Role IN ('ADMINISTRATEUR','UTILISATEUR') ),	
	FOREIGN KEY (IdCompte) REFERENCES compte (IdCompte),
	PRIMARY KEY (IdCompte, Role)
);
CREATE TABLE utilisateur (
	IdCompte		INT				NOT NULL,
	NomUtilisateur			VARCHAR(20)		NOT NULL,
	PrenomUtilisateur			VARCHAR(20) NOT NULL,
	delai INT NOT NULL,
	FOREIGN KEY (IdCompte) REFERENCES compte (IdCompte),
	PRIMARY KEY (IdCompte)
);

CREATE TABLE ami (
  IdAmi INT				NOT NULL,
  IdUtilisateur INTEGER,
  ami_id INTEGER,
  demande_envoyee BOOLEAN,
  demande_acceptee BOOLEAN,
  FOREIGN KEY (IdUtilisateur) REFERENCES utilisateur(idCompte),
  FOREIGN KEY (ami_id) REFERENCES utilisateur(idCompte),
  PRIMARY KEY(IdAmi)
);


CREATE TABLE auteur (
	IdAuteur		INT				NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	NomAuteur			VARCHAR(20)		NOT NULL,
	PRIMARY KEY (IdAuteur)
);


CREATE TABLE editeur (
	IdEditeur		INT				NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	NomEditeur			VARCHAR(20)		NOT NULL,
	PRIMARY KEY (IdEditeur)
);


CREATE TABLE categorie (
	IdCategorie		INT				NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	Libelle			VARCHAR(20)		NOT NULL,
	PRIMARY KEY (IdCategorie)
);

CREATE TABLE ouvrage (
	IdOuvrage		INT				NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	IdCompte		INT				NOT NULL,
	IdAuteur		INT				NOT NULL,
	IdEditeur		INT 			NOT NULL,
	NomOuvrage			VARCHAR(20)		NOT NULL,
	IdCategorie		INT		NOT NULL,
	FOREIGN KEY (IdAuteur) REFERENCES auteur (IdAuteur),
	FOREIGN KEY (IdCompte) REFERENCES utilisateur (IdCompte),
	FOREIGN KEY (IdCategorie) REFERENCES categorie (IdCategorie),
	FOREIGN KEY (IdEditeur) REFERENCES editeur (IdEditeur),
	PRIMARY KEY (IdOuvrage)
);

CREATE TABLE emprunt (
	IdEmprunt		INT				NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	IdOuvrage		INT				NOT NULL,
	IdCompte		INT				NOT NULL,
	DateEmprunt			VARCHAR(20)		NOT NULL,
	FOREIGN KEY (IdOuvrage) REFERENCES ouvrage (IdOuvrage),
	FOREIGN KEY (IdCompte) REFERENCES utilisateur (IdCompte),
	PRIMARY KEY (IdEmprunt)
);


