SET search_path TO projet;


-- Schéma

DROP SCHEMA IF EXISTS projet CASCADE;
CREATE SCHEMA projet AUTHORIZATION projet;
GRANT ALL PRIVILEGES ON SCHEMA projet TO projet;


-- Tables

CREATE TABLE compte (
	IdCompte		INT			 	NOT NULL	GENERATED BY DEFAULT AS IDENTITY,
	Pseudo			VARCHAR(25)		NOT NULL,
	MotDePasse		VARCHAR(25) 	NOT NULL,
	Email			VARCHAR(100)	NOT NULL,
	PRIMARY KEY (IdCompte)
);
CREATE UNIQUE INDEX idx_compte_pseudo ON compte (Pseudo ASC);

CREATE TABLE role (
	IdCompte		INT				NOT NULL,
	Role			VARCHAR(20)		NOT NULL,
	CHECK( Role IN ('ADMINISTRATEUR','UTILISATEUR') ),	
	FOREIGN KEY (IdCompte) REFERENCES compte (IdCompte),
	PRIMARY KEY (IdCompte, Role)
);

CREATE TABLE utilisateur (
	IdCompte		INT				NOT NULL,
	NomUtilisateur			VARCHAR(20)		NOT NULL,
	PrenomUtilisateur			VARCHAR(20) NOT NULL,
	FOREIGN KEY (IdCompte) REFERENCES compte (IdCompte),
	PRIMARY KEY (IdCompte)
);
CREATE TABLE auteur (
	IdAuteur		INT				NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	NomAuteur			VARCHAR(20)		NOT NULL,
	CatAuteur			VARCHAR(20),
	PRIMARY KEY (IdAuteur)
);

CREATE TABLE ouvrage (
	IdOuvrage		INT				NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	IdCompte		INT				NOT NULL,
	IdAuteur		INT				NOT NULL,
	NomOuvrage			VARCHAR(20)		NOT NULL,
	CatOuvrage			VARCHAR(20)		NOT NULL,
	FOREIGN KEY (IdAuteur) REFERENCES auteur (IdAuteur),
	FOREIGN KEY (IdCompte) REFERENCES utilisateur (IdCompte),
	PRIMARY KEY (IdOuvrage)
);

CREATE TABLE emprunt (
	IdEmprunt		INT				NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	IdOuvrage		INT				NOT NULL,
	IdCompte		INT				NOT NULL,
	NomOuvrage			VARCHAR(20)		NOT NULL,
	CatOuvrage			VARCHAR(20)		NOT NULL,
	FOREIGN KEY (IdOuvrage) REFERENCES ouvrage (IdOuvrage),
	FOREIGN KEY (IdCompte) REFERENCES utilisateur (IdCompte),
	PRIMARY KEY (IdEmprunt)
);


CREATE TABLE editeur (
	IdEditeur		INT				NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	NomEditeur			VARCHAR(20)		NOT NULL,
	PRIMARY KEY (IdEditeur)
);

